---
apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: podinfo
  annotations:
    landscaper.gardener.cloud/operation: reconcile
spec:
  componentDescriptor:
    ref:
      repositoryContext:
        type: ociRegistry
        baseUrl: ${REPOSITORY_CONTEXT}
      componentName: ${COMPONENT_NAME}
      version: ${EFFECTIVE_VERSION}

  blueprint:
    ref:
      resourceName: blueprint

  imports:
    targets:
      - name: targetCluster
        target: "#target-cluster"

  importDataMappings:
    namespace: ${IMPORT_NAMESPACE}
    ingressClass: ${IMPORT_INGRESS_CLASS}
    hostName: ${IMPORT_HOST_NAME}
...
---
apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Target
metadata:
  name: target-cluster
spec:
  type: landscaper.gardener.cloud/kubernetes-cluster
  secretRef:
    name: target-cluster-secret
    key: kubeconfig
...
